### PR TITLE
CORTX-30632: Added the submodule dispatch event

### PR DESCRIPTION
**Pull request by venkuppu-chn**
**Problem :** 
Commit hash of cortx-rgw is static at cortx repository and has to be updated manually which is quite tedious to do for every commit.

**Solution :**
Added the Github action workflow which will dispatch the event with latest commit hash of cortx-rgw to parent cortx repo.
 

Signed-off-by: Venkatesh K <venkatesh.k@seagate.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by mukul-seagate11 — APPROVED** [review]
looks good

**Comment by andriytk** [comment]
> Problem : There is no submodule found in parent repo for cortx-rgw

Sorry, I cannot get it. Which submodule and why it is a problem?

**Comment by mukul-seagate11** [comment]
> > Problem : There is no submodule found in parent repo for cortx-rgw
> 
> Sorry, I cannot get it. Which submodule and why it is a problem?

@andriytk, This PR is to create linking of submodule as cortx-rgw in parent repo i.e. https://github.com/Seagate/cortx

**Comment by andriytk** [comment]
> @andriytk, This PR is to create linking of submodule as cortx-rgw in parent repo i.e. https://github.com/Seagate/cortx

Please, update the PR description with this information.

**Comment by venkuppu-chn** [comment]
> > @andriytk, This PR is to create linking of submodule as cortx-rgw in parent repo i.e. https://github.com/Seagate/cortx
> 
> Please, update the PR description with this information. And please elaborate - why is this linking needed, what is it for. Thanks.

They are a quick visual indicator to the community where else they can other software relevant to cortx.

**Review by andriytk — APPROVED** [review]

**Comment by mukul-seagate11** [comment]
@gatekeepers, please merge the PR as already approved

**Pull request merged**
