### PR TITLE
rgw_sal_motr : [CORTX-33574] Fixed  Object tagging tests failing intermittently issue

### PR DESCRIPTION
**Pull request by shraddhaghatol**
**Problem** : Object tagging tests were failing intermittently due to tags were not set through setObjectTagging API.

**Solution** : For multipart object case, in setObjectTagging API, code was returning success code without setting tag values to given object hence removing this code.For Multipart objects, tagging support is already handled in different flow.

Signed-off-by: shraddhaghatol <shraddha.j.ghatol@seagate.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by shraddhaghatol** [comment]
Ceph tests got passed successfully  https://jts.seagate.com/browse/CORTX-33574?focusedCommentId=2411814&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2411814

**Review by shriya-deshmukh — APPROVED** [review]

**Review by priyanka25081999 — APPROVED** [review]
LGTM

**Comment by shraddhaghatol** [comment]
CFT tests are successful.
https://jts.seagate.com/browse/CORTX-33574?focusedCommentId=2412060&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2412060

**Comment by shraddhaghatol** [comment]
Done manual testing which includes simple and Multipart object tagging testing with versioning.
https://jts.seagate.com/browse/CORTX-33574?focusedCommentId=2412056&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2412056

**Pull request merged**
