### PR TITLE
Close connection with Motr

### PR DESCRIPTION
**Pull request by sachinpunadikar**
While destructing MotrStore object, close connection with motr.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [X] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [X] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [X] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [X] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by kupranay — APPROVED** [review]

**Review by bkirunge7 — COMMENTED** [review]
@andriytk @siningwuseagate can you pls review this

**Review by bkirunge7 — APPROVED** [review]

**Review by andriytk — APPROVED** [review]
Just curious - what happens if we don't do this?

**Comment by sachinpunadikar** [comment]
> Just curious - what happens if we don't do this?

2 scenarios 
1. When we need to restart rgw for some reason - one needs to run hctl shutdown & hctl start before restarting rgw
2. While running radosgw-admin tool, every time we need to do hctl shutdown & start , which is not practical

**Comment by andriytk** [comment]
Thanks. Let's create one more PR with this to the ceph repo?

**Comment by sachinpunadikar** [comment]
> Thanks. Let's create one more PR with this to the ceph repo?

Sure

**Pull request merged**
