### PR TITLE
rgw_sal_motr :[CORTX-33109] Fixed noSuchKey error in CopyObject API for IAM Policy

### PR DESCRIPTION
**Pull request by shraddhaghatol**
Problem : 
"NoSuchKey" error was returning when tried copyObject API after applying valid IAM policy on IAM user.

Solution : 
Previously in copy object API it was considering owner of destination bucket as "user id" and not the actual owner of the bucket. Fixed that by changing owner as destination bucket owner.

Sample policy example with command is given in - https://jts.seagate.com/browse/CORTX-33109?focusedCommentId=2421624&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2421624

Signed-off-by: shraddhaghatol <shraddha.j.ghatol@seagate.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by priyanka25081999 — APPROVED** [review]
Looks good

**Review by shriya-deshmukh — APPROVED** [review]

**Review by sachitanands — APPROVED** [review]
looks good

**Review by cdeshmukh — COMMENTED** [review]
> Problem :
"NoSuchKey" error was returning when tried copyObject API after applying valid IAM policy on IAM user.

Add exact policy with commands, that way anyone can try recreating it.

Am fine with changes otherwise.

**Comment by shraddhaghatol** [comment]
retest this please

**Comment by shraddhaghatol** [comment]
ran s3 ceph test suite. All tests are passed apart from known failures. Job link - 
https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/S3Server/job/S3-Compatibility-Test-Ceph-RGW/214/#showFailuresLink
image

**Review by cdeshmukh — APPROVED** [review]

**Pull request merged**
