### PR TITLE
rgw_sal_motr: [CORTX-33105] - Handle errors for copy object operation

### PR DESCRIPTION
**Pull request by shraddhaghatol**
Problem statement: Handle errors for copy object operation

Solution: Added detailed error message and changed some error codes to make it AWS compliance. 

Signed-off-by: shraddhaghatol <shraddha.j.ghatol@seagate.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by cdeshmukh — APPROVED** [review]

**Review by shriya-deshmukh — APPROVED** [review]

**Review by priyanka25081999 — APPROVED** [review]

**Review by sachitanands — APPROVED** [review]
looks good

**Comment by cdeshmukh** [comment]
@shraddhaghatol as suggested by @sachitanands in DSU, please run existing S3 automated testcases, S3 splunk tests to confirm if any tests are breaking because of these changes (which are to align with AWS S3 behavior) and let QA team know, so that they can make the required changes in tests code

**Comment by cdeshmukh** [comment]
image
https://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Cortx-Deployment/job/Generic/job/cortx-rgw/100/

1N Deployment was good before rebase

**Comment by shraddhaghatol** [comment]
With this PR following test cases will be failed -
14:48:36  ======================================================================
14:48:36  FAIL: s3tests_boto3.functional.test_s3.test_get_object_ifnonematch_good
14:48:36  ----------------------------------------------------------------------
14:48:36  Traceback (most recent call last):
14:48:36    File "/root/compatability-test/ceph/cortx-re/scripts/automation/s3-test/s3-tests/virtualenv/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
14:48:36      self.test(*self.arg)
14:48:36    File "/root/compatability-test/ceph/cortx-re/scripts/automation/s3-test/s3-tests/s3tests_boto3/functional/test_s3.py", line 3538, in test_get_object_ifnonematch_good
14:48:36      eq(status, 304)
14:48:36  AssertionError: 412 != 304
14:48:36  >>  raise AssertionError(None or "%r != %r" % (412, 304))


14:48:36  ======================================================================
14:48:36  FAIL: s3tests_boto3.functional.test_s3.test_get_object_ifmodifiedsince_failed
14:48:36  ----------------------------------------------------------------------
14:48:36  Traceback (most recent call last):
14:48:36    File "/root/compatability-test/ceph/cortx-re/scripts/automation/s3-test/s3-tests/virtualenv/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
14:48:36      self.test(*self.arg)
14:48:36    File "/root/compatability-test/ceph/cortx-re/scripts/automation/s3-test/s3-tests/s3tests_boto3/functional/test_s3.py", line 3589, in test_get_object_ifmodifiedsince_failed
14:48:36      eq(status, 304)
14:48:36  AssertionError: 412 != 304
14:48:36  >>  raise AssertionError(None or "%r != %r" % (412, 304))

Job link:: https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/S3Server/job/S3-Compatibility-Test-Ceph-RGW/176/console

**Pull request merged**
